-- ---------------------------------------------------------------------------
-- Starter data. Runs automatically on `supabase db reset`.
--
-- No user accounts here: create yours in the Supabase Dashboard
-- (Authentication -> Users -> Add user), then promote it to admin with
--
--   update public.profiles set role = 'admin' where id = '<the auth user id>';
--
-- There is deliberately nothing else. This used to seed a template and a
-- campaign; migration 0025 removed both tables. Leads arrive from the Google
-- Sheet, and the draft generator composes from the lead's own research rather
-- than from a stored template, so a fresh project needs no starter rows at all.
-- ---------------------------------------------------------------------------
