import { NextResponse, type NextRequest } from 'next/server';
import { z } from 'zod';

import { assertAdmin } from '@/lib/auth/session';
import { recordActivity } from '@/lib/services/activity';
import { buildGenerationContext, generateEmail, getActiveGenerator } from '@/lib/services/ai';
import { buildSystemPrompt, buildUserPrompt } from '@/lib/services/ai/prompt';
import { createEmailVersion } from '@/lib/services/email-versions';
import { syncLeadChange } from '@/lib/services/sync';
import { EMAIL_TYPE_LABELS } from '@/lib/pipeline/labels';

/**
 * POST /api/admin/leads/:id/regenerate
 *
 * Body: { "type": "initial" | "followup1" | "followup2", "preview"?: boolean }
 *
 * Generates a fresh draft and saves it as a NEW version, leaving every previous
 * version intact and re-activatable. `preview: true` returns the generated text
 * and the exact prompt without writing anything useful for tuning a model
 * without filling the history with throwaway versions.
 *
 * Why a route handler as well as the Server Action:
 *   * the action (`lib/actions/review.ts`) is what the UI calls;
 *   * this endpoint is what anything outside the browser calls a script, a
 *     bulk backfill, or an external tool.
 * Both funnel into the same generateEmail() + createEmailVersion() pair, so
 * there is one code path and one set of rules.
 *
 * Which engine actually produces the text is the `ai.provider` setting:
 * `template` (deterministic, offline, the default) or `ollama` (a local model).
 *
 * Authorization: /api/admin is in the middleware's ADMIN_PREFIXES, but
 * middleware is not a security boundary for a route handler assertAdmin()
 * below is, and RLS is the backstop under that.
 */

export const dynamic = 'force-dynamic';

const bodySchema = z.object({
  type: z.enum(['initial', 'followup1', 'followup2']),
  preview: z.boolean().optional(),
});

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  let userId: string;
  try {
    const session = await assertAdmin();
    userId = session.user.id;
  } catch {
    return NextResponse.json({ ok: false, message: 'Unauthorized.' }, { status: 401 });
  }

  const { id: leadId } = await params;
  if (!z.uuid().safeParse(leadId).success) {
    return NextResponse.json({ ok: false, message: 'Invalid lead id.' }, { status: 400 });
  }

  const raw = await request.json().catch(() => null);
  const parsed = bodySchema.safeParse(raw);
  if (!parsed.success) {
    return NextResponse.json(
      { ok: false, message: 'Body must be { type: "initial" | "followup1" | "followup2" }.' },
      { status: 400 },
    );
  }

  const { type, preview } = parsed.data;

  if (preview) {
    const built = await buildGenerationContext(leadId, type);
    if (!built.ok) {
      return NextResponse.json({ ok: false, message: built.message }, { status: 404 });
    }

    const generator = await getActiveGenerator();
    const result = await generator.generate(built.context);

    return NextResponse.json(
      {
        ok: result.ok,
        message: result.message,
        provider: generator.id,
        // The prompt is returned so a bad draft can be diagnosed as a prompt
        // problem or a model problem without guessing.
        prompt: { system: buildSystemPrompt(), user: buildUserPrompt(built.context) },
        email: result.email,
        saved: false,
      },
      { status: result.ok ? 200 : 502 },
    );
  }

  const generation = await generateEmail(leadId, type);
  if (!generation.ok || !generation.email) {
    // 502: the request was fine, the generator was not.
    return NextResponse.json({ ok: false, message: generation.message }, { status: 502 });
  }

  const created = await createEmailVersion({
    leadId,
    type,
    subject: generation.email.subject,
    content: generation.email.content,
    generatedBy: generation.email.generatedBy,
    createdBy: userId,
    activate: true,
  });

  if (!created.ok || !created.version) {
    return NextResponse.json({ ok: false, message: created.message }, { status: 500 });
  }

  await recordActivity({
    leadId,
    kind: 'draft_regenerated',
    summary: `${EMAIL_TYPE_LABELS[type]} regenerated version ${created.version.version_number}`,
    detail: `Generated by ${generation.email.generatedBy} via the API.`,
    actorId: userId,
  });

  await syncLeadChange(leadId, [type === 'initial' ? 'draft' : type]);

  return NextResponse.json({
    ok: true,
    message: created.message,
    provider: generation.email.generatedBy,
    saved: true,
    version: {
      id: created.version.id,
      type: created.version.type,
      version_number: created.version.version_number,
      subject: created.version.subject,
      content: created.version.content,
      active: created.version.active,
      status: created.version.status,
      created_at: created.version.created_at,
    },
  });
}
